### ISSUE TITLE
🚀 [REQUEST] - Add Support for PEFT (LoRA) settting to `evalverse`

### ISSUE THREAD

**Issue by SeungyounShin** [UpstageAI/evalverse#19]
### Feature request

The current setup in the evalverse repository relies on the lm_eval library for model evaluations. However, the command-line interface provided does not support the addition of the PEFT (LoRA) tuning parameters directly. Given the increasing popularity and significance of LoRA tuning in model performance enhancement, it is crucial to enable this functionality within the evalverse framework.

Advanced usage tips for lm_eval suggest that arguments provided via `--model_args` get passed directly to the constructor, allowing for functionalities like PEFT to be specified:

```
lm_eval --model hf \
    --model_args pretrained=EleutherAI/gpt-j-6b,parallelize=True,load_in_4bit=True,peft=nomic-ai/gpt4all-j-lora \
    --tasks openbookqa,arc_easy,winogrande,hellaswag,arc_challenge,piqa,boolq \
    --device cuda:0
```

I propose that similar functionality be integrated into evalverse, thereby expanding the versatility of the repository for contemporary NLP research and applications that benefit from PEFT tuning methods like LoRA.

### Context

The integration of PEFT (LoRA) tuning into the evalverse repository is motivated by the growing need for more refined and specialized tuning methods in the NLP community. LoRA tuning has shown to provide substantial benefits in model performance without the extensive computational cost of full model finetuning. By enabling PEFT support, evalverse can stay abreast with the latest advancements in NLP and provide researchers and practitioners with the necessary tools to leverage these improvements.

**Comment by SeungyounShin** [comment]
Can I write a draft PR for this?

**Comment by SONG-WONHO** [comment]
@SeungyounShin Sure. We understand the importance of Peft and we think it will be a great feature to have in evalverse. We'd be happy if you write a draft PR for this. (cc. @jihoo-kim)

**Comment by SeungyounShin** [comment]
Upon reflection and a deeper dive into the specifics of the tools we're wrapping, I've come to understand that while `lm_eval` does indeed support the `peft` parameter, other key components of our evaluation ecosystem, such as `llm_judge` and `eq-bench`, do not. Given that `evalverse` serves as an overarching framework designed to seamlessly integrate with a variety of evaluation tools – some of which do not accommodate `peft` parameters – I propose that we continue without integrating `peft` directly into `evalverse`'s interface.

Additionally, it might be beneficial for users if there's a recommendation or guideline suggesting the integration of PEFT weights with the base model prior to submission to `evalverse`. This approach could streamline the evaluation process for models utilizing PEFT tuning.

So I close this issue for now
